mod.mc_dep_forgelike=[1.20.1]
mod.mc_dep_fabric=1.20.1
mod.ftb_quests_dep_forgelike=*
mod.ftb_quests_dep_fabric=*
mod.ftb_library_dep_forgelike=[2001.2,)
mod.mc_title=1.20.1
mod.mc_targets=1.20 1.20.1
mod.pack_format=15

deps.forge_loader=47.4.20
deps.neoforge_loader=[UNSUPPORTED]
deps.fabric_api=0.92.11+1.20.1

deps.ftb_quests=2001.4.21
deps.ftb_library=2001.2.9
deps.ftb_teams=2001.3.2
deps.architectury=9.1.12
deps.cloth_config=11.1.136
deps.mod_menu=7.2.2
deps.fancy_toasts=3gosntSs
