modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://www.curseforge.com/minecraft/mc-mods/ftb-quests-entity-visualization"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ftb-quests-entity-visualization"
authors = "Sxilverr"
description = "Adds entity visualization to FTB Quests."
logoFile = "assets/${id}/icon.png"

[[mixins]]
config = "ftbquestsentityvis.mixins.json"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "ftbquests"
type = "required"
versionRange = "${ftb_quests_dep}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${id}]]
modId = "ftblibrary"
type = "required"
versionRange = "${ftb_library_dep}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${id}]]
modId = "questsadditions"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${id}]]
modId = "fancytoasts"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"
