mod.mc_dep_forgelike=[1.21.1]
mod.mc_dep_fabric=1.21.1
mod.ftb_quests_dep_forgelike=[2101.1.29,)
mod.ftb_quests_dep_fabric=>=2101.1.29
mod.ftb_library_dep_forgelike=[2101.1,)
mod.mc_title=1.21.1
mod.mc_targets=1.21 1.21.1
mod.pack_format=34

deps.forge_loader=[UNSUPPORTED]
deps.neoforge_loader=21.1.213
deps.fabric_api=0.116.14+1.21.1

deps.ftb_quests=2101.1.29
deps.ftb_library=2101.1.34
deps.architectury=13.0.8
deps.cloth_config=15.0.140
deps.mod_menu=11.0.4
deps.fancy_toasts=u38wSDqe
